services:
  vpn:
    container_name: l2tp-vpn
    image: hwdsl2/ipsec-vpn-server
    restart: always
    privileged: true
    ports:
      - 500:500/udp
      - 4500:4500/udp
    env_file: 
      - ./vpn.env
    volumes:
      - /data/l2tp-data:/etc/ipsec.d
      - /lib/modules:/lib/modules:ro
  shadowsocks:
    container_name: ss-rust
    restart: always
    image: teddysun/shadowsocks-rust
    ports:
      - 9000:9000
      - 9000:9000/udp
    volumes:
      - ./shadowsocks-config.json:/etc/shadowsocks-rust/config.json
