services:
  shadowsocks:
    container_name: ss-rust
    restart: always
    image: teddysun/shadowsocks-rust
    ports:
      - 9000:9000
      - 9000:9000/udp
    volumes:
      - /opt/shadowsocks-config.json:/etc/shadowsocks-rust/config.json
